language: node_js
node_js:
  - "4"
before_script: 
  - SCRT=$SECRETTEST echo "INSTALL Secret"
  - git lfs pull
script:
  - |
      SCRT=$SECRETTEST
      if [ "${SCRT}" == "some-secret" ]; then
        echo "TEST Secret"
      else
        echo "TEST Fail"
      fi
