language: node_js
node_js:
  - "4"
before_script: 
  - SCRT=$SECRETTEST echo "INSTALL Secret: $SCRT, General secret: $SECRETTEST!"
  - git lfs pull
script:
  - SCRT=$SECRETTEST echo "TEST Secret: $SCRT, General secret: $SECRETTEST!"
