language: node_js
node_js:
  - "4"
script:
  - echo "test"
after_script:
  - |
      if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
        REPO_SLUG_ARRAY=(${TRAVIS_REPO_SLUG//\// })
        DEPLOY_DOMAIN="pr-${TRAVIS_PULL_REQUEST}-${REPO_SLUG_ARRAY[1]}-${REPO_SLUG_ARRAY[0]}.surge.sh"
        npm install surge
        mkdir reports-surge
        mkdir reports-surge/gemini-coverage
        mkdir reports-surge/gemini-report
        cp index.html reports-surge/gemini-coverage
        cp index.html reports-surge/gemini-report
        surge -p reports-surge -d ${DEPLOY_DOMAIN}
        curl -H "Authorization: token ${GITHUB_TOKEN}" \
          --request POST "https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/comments" \
          --data '{"body":"Travis automatic deployment:\n\n- '${DEPLOY_DOMAIN}/gemini-coverage'\n- '${DEPLOY_DOMAIN}/gemini-report'"}'
      fi
